FROM registry.cn-hangzhou.aliyuncs.com/mj520/golang-build
#glibc
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub "https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub" && \
    wget "https://ghproxy.com/https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk" && \
    apk add glibc-2.35-r0.apk && \
    wget "https://ghproxy.com/https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-bin-2.35-r0.apk" && \
    wget "https://ghproxy.com/https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-i18n-2.35-r0.apk" && \
    apk add glibc-bin-2.35-r0.apk glibc-i18n-2.35-r0.apk && \
    /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8 && \
    rm -rf glibc-*.apk && \
    /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib && \
    ln -s /usr/glibc-compat/etc/ld.so.conf /etc/ld.so.conf && \
    ls -l /usr/glibc-compat